<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Emgu.CV" Version="4.10.0.5680" />
		<PackageReference Include="Emgu.CV.Bitmap" Version="4.10.0.5680" />
		<PackageReference Include="Emgu.CV.runtime.windows" Version="4.10.0.5680" />
		<PackageReference Include="Emgu.CV.UI" Version="4.10.0.5680" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Models\age_deploy.prototxt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Models\age_net.caffemodel">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Models\gender_deploy.prototxt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Models\gender_net.caffemodel">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\emotion-ferplus-12-int8.onnx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\emotion-ferplus-2.onnx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Resources\emotion-ferplus-8.onnx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
